---
# Set environment variable for each machine seperatley and launch ROS nodes
- hosts: all
  become: yes
  tasks:
    - name: source the ROS workspace && Launch the ROS nodes
      ansible.builtin.script: ~/run.sh