---
- name: Create a directory, clone a Github repository, build the repository, and launch ROS nodes
  hosts: all
  become: no
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ~/ansible_automation/production/run.sh
        dest: ~/run.sh
        mode: 0755
    - name: Remove the directory if it exists and then rewrite on it
      file:
        path: ~/turtlebot4_bringup/src
        state: absent

    - name: Create a ROS2 workspace directory
      file:
        path: ~/turtlebot4_bringup/src
        state: directory

    - name: Clone the Github repository
      git:
        repo: https://github.com/swarmBots-ipa/turtlebot4_robot.git
        dest: ~/turtlebot4_bringup/src

    - name: Build the repository using colcon
      command: colcon build
      args:
        chdir: ~/turtlebot4_bringup